version: '3.8'

services:
  api:
    container_name: drive-pulse-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    # Removed env_file directive
    environment:
      API_PORT: 8080
      # Explicitly define DATABASE_URL for inter-service communication
      # Using the internal service name 'db' and its default internal port '27017'
      DATABASE_URL: mongodb://root:password@db:27017/drive-pulse?authSource=admin
    ports:
      # Map the host port (API_PORT from .env) to the container's internal port
      - '8080:8080' # Explicitly use 8080 from .env, or use variable if Koyeb supports
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - drive-pulse-net
    command: yarn start:dev

  db:
    container_name: drive-pulse-db
    build:
      context: .
      dockerfile: Dockerfile
    # command: ['--config', '/etc/mongod.conf']
    restart: always
    # Removed env_file directive
    environment:
      # Explicitly define environment variables for MongoDB initialization
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: drive-pulse
    ports:
      # Map the host port (MONGO_PORT from .env) to the container's internal port
      - '27018:27017' # Explicitly use 27018 from .env
    volumes:
      - mongodb_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
    networks:
      - drive-pulse-net

volumes:
  mongodb_data:
    driver: local

networks:
  drive-pulse-net:
    driver: bridge
